package com.company.payments.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * RBM Reporting Service.
 * Generates scheduled reports for the Reserve Bank of Malawi:
 * - Daily transaction volume summaries
 * - Monthly liquidity position reports
 * - SARs (Suspicious Activity Reports) — generated by AmlService
 * 
 * Reports are exported as CSV/PDF to the configured output directory.
 */
@Service
public class ReportingService {

    private static final Logger log = LoggerFactory.getLogger(ReportingService.class);
    private static final String REPORTS_DIR = "reports";

    /**
     * Daily transaction volume report — runs at midnight every day.
     */
    @Scheduled(cron = "0 0 0 * * *")
    public void generateDailyTransactionReport() {
        String date = LocalDate.now().minusDays(1).format(DateTimeFormatter.ISO_DATE);
        String filename = String.format("transaction_volume_%s.csv", date);

        log.info("[REPORTING] Generating daily transaction report for {}", date);

        try {
            Path dir = Paths.get(REPORTS_DIR);
            Files.createDirectories(dir);

            try (PrintWriter pw = new PrintWriter(new FileWriter(dir.resolve(filename).toFile()))) {
                // CSV Header
                pw.println("date,total_deposits,total_withdrawals,total_fx_trades,net_position,currency");

                // In production: query from ledger_entries grouped by type and date
                // Placeholder data for template:
                pw.printf("%s,%s,%s,%s,%s,%s%n",
                        date,
                        "0.00",   // total_deposits
                        "0.00",   // total_withdrawals
                        "0",      // total_fx_trades
                        "0.00",   // net_position
                        "MWK"
                );
            }

            log.info("[REPORTING] Daily report generated: {}", filename);
        } catch (IOException e) {
            log.error("[REPORTING] Failed to generate daily report", e);
        }
    }

    /**
     * Monthly liquidity position report — runs on the 1st of each month.
     */
    @Scheduled(cron = "0 0 1 1 * *")
    public void generateMonthlyLiquidityReport() {
        String month = LocalDate.now().minusMonths(1).format(DateTimeFormatter.ofPattern("yyyy-MM"));
        String filename = String.format("liquidity_position_%s.csv", month);

        log.info("[REPORTING] Generating monthly liquidity report for {}", month);

        try {
            Path dir = Paths.get(REPORTS_DIR);
            Files.createDirectories(dir);

            try (PrintWriter pw = new PrintWriter(new FileWriter(dir.resolve(filename).toFile()))) {
                pw.println("month,currency,total_inflows,total_outflows,net_position,reserve_balance");
                pw.printf("%s,%s,%s,%s,%s,%s%n",
                        month, "MWK", "0.00", "0.00", "0.00", "0.00");
                pw.printf("%s,%s,%s,%s,%s,%s%n",
                        month, "USD", "0.00", "0.00", "0.00", "0.00");
            }

            log.info("[REPORTING] Monthly liquidity report generated: {}", filename);
        } catch (IOException e) {
            log.error("[REPORTING] Failed to generate monthly report", e);
        }
    }

    /**
     * Reconciliation summary report — runs daily after reconciliation.
     */
    @Scheduled(cron = "0 30 0 * * *")
    public void generateReconciliationReport() {
        String date = LocalDate.now().minusDays(1).format(DateTimeFormatter.ISO_DATE);
        String filename = String.format("reconciliation_report_%s.csv", date);

        log.info("[REPORTING] Generating reconciliation report for {}", date);

        try {
            Path dir = Paths.get(REPORTS_DIR);
            Files.createDirectories(dir);

            try (PrintWriter pw = new PrintWriter(new FileWriter(dir.resolve(filename).toFile()))) {
                pw.println("date,provider,matched_count,mismatched_count,missing_count,total_amount_matched");
                // In production: query reconciliation_events table
                pw.printf("%s,%s,%d,%d,%d,%s%n", date, "airtel", 0, 0, 0, "0.00");
                pw.printf("%s,%s,%d,%d,%d,%s%n", date, "tnm", 0, 0, 0, "0.00");
            }

            log.info("[REPORTING] Reconciliation report generated: {}", filename);
        } catch (IOException e) {
            log.error("[REPORTING] Failed to generate reconciliation report", e);
        }
    }
}
