package com.company.payments.worker;

import com.company.payments.service.LedgerService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.UUID;

@Component
public class WebhookConsumer {

    private static final Logger log = LoggerFactory.getLogger(WebhookConsumer.class);
    private final LedgerService ledgerService;
    private final ObjectMapper mapper;

    public WebhookConsumer(LedgerService ledgerService, ObjectMapper mapper) {
        this.ledgerService = ledgerService;
        this.mapper = mapper;
    }

    @KafkaListener(topics = "incoming-webhooks", groupId = "payments-core-group")
    public void consumeWebhookPayload(String message) {
        log.info("Received raw webhook payload from queue");

        try {
            JsonNode payload = mapper.readTree(message);

            // Extract the fields generated by Airtel/TNM connectors
            String idempotencyTxId = payload.get("provider_tx_id").asText();
            String walletIdStr = payload.get("wallet_id").asText();
            double parseAmount = payload.get("amount").asDouble();
            String currency = payload.get("currency").asText();

            ledgerService.recordEntry(
                    UUID.fromString(walletIdStr),
                    UUID.fromString(idempotencyTxId), // Used as idempotency dedupe key
                    "DEPOSIT",
                    BigDecimal.valueOf(parseAmount),
                    currency,
                    payload
            );

            log.info("Successfully processed deposit webhook and inserted ledger entry for TxId: {}", idempotencyTxId);

        } catch (Exception e) {
            log.error("Failed to parse and apply webhook to ledger. Triggering consumer backoff retry.", e);
            // Throwing triggers Spring Kafka's DefaultErrorHandler backoff mechanism
            throw new RuntimeException("Consumer retry triggered", e);
        }
    }
}
